### PR TITLE
Removal of connection profiles

### PR DESCRIPTION
**Pull request by AliveDevil**

### CODE REVIEW

**Comment by AliveDevil** [comment]
@dkocher Your part, update Maven projects in order to get the default-profiles into the profiles folder, and update build scripts to reflect the changes.

**Comment by dkocher** [comment]
Depends on iterate-ch/docs#246.

**Comment by dkocher** [comment]
> @dkocher Your part, update Maven projects in order to get the default-profiles into the profiles folder, and update build scripts to reflect the changes.

I would keep `profiles/default` here which should allow to keep the build process as is. Only move no default third party connection profiles in `profiles/*.cyberduckprofile` to the iterate-ch/docs repository.

**Review by dkocher — APPROVED** [review]

**Comment by dkocher** [comment]
The alternate [repository](https://github.com/iterate-ch/profiles) has been setup.

**Pull request merged**
