### PR TITLE
Catch errors on validate command

### LINKED ISSUE #15151: Crash on Disconnect
```
Anwendung: Cyberduck.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: java.lang.IllegalStateException
   bei org.apache.http.util.Asserts.check(Boolean, System.String)
   bei org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(org.apache.http.conn.routing.HttpRoute, System.Object)
   bei org.apache.http.impl.execchain.MainClientExec.execute(org.apache.http.conn.routing.HttpRoute, org.apache.http.client.methods.HttpRequestWrapper, org.apache.http.client.protocol.HttpClientContext, org.apache.http.client.methods.HttpExecutionAware)
   bei org.apache.http.impl.execchain.ProtocolExec.execute(org.apache.http.conn.routing.HttpRoute, org.apache.http.client.methods.HttpRequestWrapper, org.apache.http.client.protocol.HttpClientContext, org.apache.http.client.methods.HttpExecutionAware)
   bei org.apache.http.impl.execchain.RetryExec.execute(org.apache.http.conn.routing.HttpRoute, org.apache.http.client.methods.HttpRequestWrapper, org.apache.http.client.protocol.HttpClientContext, org.apache.http.client.methods.HttpExecutionAware)
   bei org.apache.http.impl.execchain.ServiceUnavailableRetryExec.execute(org.apache.http.conn.routing.HttpRoute, org.apache.http.client.methods.HttpRequestWrapper, org.apache.http.client.protocol.HttpClientContext, org.apache.http.client.methods.HttpExecutionAware)
   bei org.apache.http.impl.execchain.RedirectExec.execute(org.apache.http.conn.routing.HttpRoute, org.apache.http.client.methods.HttpRequestWrapper, org.apache.http.client.protocol.HttpClientContext, org.apache.http.client.methods.HttpExecutionAware)
   bei org.apache.http.impl.client.InternalHttpClient.doExecute(org.apache.http.HttpHost, org.apache.http.HttpRequest, org.apache.http.protocol.HttpContext)
   bei org.apache.http.impl.client.CloseableHttpClient.execute(org.apache.http.client.methods.HttpUriRequest, org.apache.http.protocol.HttpContext)
   bei com.github.sardine.impl.SardineImpl.execute(org.apache.http.client.protocol.HttpClientContext, org.apache.http.client.methods.HttpRequestBase, org.apache.http.client.ResponseHandler)
   bei com.github.sardine.impl.SardineImpl.execute(org.apache.http.client.methods.HttpRequestBase)
   bei ch.cyberduck.core.dav.DAVClient.execute(org.apache.http.client.methods.HttpRequestBase)
   bei ch.cyberduck.core.dav.DAVReadFeature.read(ch.cyberduck.core.Path, ch.cyberduck.core.transfer.TransferStatus, ch.cyberduck.core.ConnectionCallback)
   bei ch.cyberduck.core.cryptomator.ContentReader.read(ch.cyberduck.core.Path)
   bei ch.cyberduck.core.cryptomator.CryptoVault.readVaultConfig(ch.cyberduck.core.Session)
   bei ch.cyberduck.core.cryptomator.CryptoVault.unlock(ch.cyberduck.core.Session, ch.cyberduck.core.PasswordCallback, ch.cyberduck.core.Host, System.String)
   bei ch.cyberduck.core.cryptomator.CryptoVault.load(ch.cyberduck.core.Session, ch.cyberduck.core.PasswordCallback)
   bei ch.cyberduck.core.cryptomator.CryptoVault.<bridge>load(ch.cyberduck.core.Session, ch.cyberduck.core.PasswordCallback)
   bei ch.cyberduck.core.vault.LoadingVaultLookupListener.load(ch.cyberduck.core.Session, ch.cyberduck.core.Path, System.String, System.String, Byte[])
   bei ch.cyberduck.core.vault.DefaultVaultRegistry.find(ch.cyberduck.core.Session, ch.cyberduck.core.Path, Boolean)
   bei ch.cyberduck.core.vault.VaultRegistry.<default>find(ch.cyberduck.core.vault.VaultRegistry, ch.cyberduck.core.Session, ch.cyberduck.core.Path)
   bei ch.cyberduck.core.vault.registry.VaultRegistryDirectoryFeature.isSupported(ch.cyberduck.core.Path, System.String)
   bei Ch.Cyberduck.Ui.Core.Commands+Command.Validate()
   bei Ch.Cyberduck.Ui.Core.Commands.Validate()
   bei System.EventHandler.Invoke(System.Object, System.EventArgs)
   bei System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32)
   bei System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   bei System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   bei System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   bei Ch.Cyberduck.Ui.Program.Main(System.String[])

```

### PR DESCRIPTION
**Pull request by AliveDevil**
Relates #15151

### CODE REVIEW

**Comment by dkocher** [comment]
Possibly redundant with #15154.

**Comment by AliveDevil** [comment]
try-catch is "free" unless an exception is thrown. Validation will now don't take down the app, if an exception is thrown.
Not really redundant - just another fail safe.

**Comment by AliveDevil** [comment]
Changed Fixes to Relates, as this only circumvents the underlying issue.

**Comment by dkocher** [comment]
> try-catch is "free" unless an exception is thrown. Validation will now don't take down the app, if an exception is thrown. Not really redundant - just another fail safe.

Should this then be added for all validation features?

**Comment by AliveDevil** [comment]
> all validation features

This is already available to all validation commands in Cyberduck Windows now (all UI buttons are now catched in this way), as it is the most common location where the validation delegate is called.

**Review by dkocher — APPROVED** [review]

**Pull request merged**
