### PR TITLE
Do not send any If header if pseudo locking is enabled.

### PR DESCRIPTION
**Pull request by ylangisc**
Do not send any If header if pseudo locking is enabled.

### CODE REVIEW

**Review by dkocher — COMMENTED** [review]
The caller should nullify the `lockid` in the transfer status instead.

**Comment by ylangisc** [comment]
> The caller should nullify the `lockid` in the transfer status instead.

What about making the check when looking up the feature at https://github.com/iterate-ch/cyberduck/blob/master/webdav/src/main/java/ch/cyberduck/core/dav/DAVSession.java#L342-L344?

**Comment by dkocher** [comment]
> > The caller should nullify the `lockid` in the transfer status instead.
> 
> What about making the check when looking up the feature at https://github.com/iterate-ch/cyberduck/blob/master/webdav/src/main/java/ch/cyberduck/core/dav/DAVSession.java#L342-L344?

We can add a property like `webdav.lock.enable` which allows disabling lock feature ignoring support by the server.

**Comment by dkocher** [comment]
> > > The caller should nullify the `lockid` in the transfer status instead.
> > 
> > 
> > What about making the check when looking up the feature at https://github.com/iterate-ch/cyberduck/blob/master/webdav/src/main/java/ch/cyberduck/core/dav/DAVSession.java#L342-L344?
> 
> We can add a property like `webdav.lock.enable` which allows disabling lock feature ignoring support by the server.

In #13580.

**Pull request closed without merging**
