### PR TITLE
Allow to override authentication strategy in subclasses.

### LINKED ISSUE #15177: Allow for injection of OAuth2RequestInterceptor and STSAssumeRoleCredentialsRequestInterceptor
**Describe the solution you'd like**
Factory for `OAuth2RequestInterceptor` and `STSAssumeRoleCredentialsRequestInterceptor` to inject implementations extending those two interceptors.

### PR DESCRIPTION
**Pull request by dkocher**

### CODE REVIEW

**Comment by chenkins** [comment]
@dkocher Can `STSAssumeRoleAuthorizationService.service` be made `protected` as in #15178 ? Otherwise subclasses may need to duplicate the code for creating the service, then pass it to the `super` constructor and have a duplicate `private`  service field with the same instance.

**Review by chenkins — CHANGES_REQUESTED** [review]
@dkocher Can `STSAssumeRoleAuthorizationService.service` be made `protected` as in #15178 ? Otherwise subclasses may need to duplicate the code for creating the service, then pass it to the `super` constructor and have a duplicate `private`  service field with the same instance.

**Review by chenkins — CHANGES_REQUESTED** [review]
Still need to duplicate
```
AWSSecurityTokenServiceClientBuilder
                .standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(bookmark.getProtocol().getSTSEndpoint(), null))
                .withCredentials(new AWSStaticCredentialsProvider(new AnonymousAWSCredentials()))
                .withClientConfiguration(new CustomClientConfiguration(bookmark,
                        new ThreadLocalHostnameDelegatingTrustManager(trust, bookmark.getProtocol().getSTSEndpoint()), key))
                .build()
```
and the field holding it if I need the `service` in subclasses of `STSAssumeRoleAuthorizationService` - is this on purpose?

**Comment by dkocher** [comment]
> Still need to duplicate
> 
> ```
> AWSSecurityTokenServiceClientBuilder
>                 .standard()
>                 .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(bookmark.getProtocol().getSTSEndpoint(), null))
>                 .withCredentials(new AWSStaticCredentialsProvider(new AnonymousAWSCredentials()))
>                 .withClientConfiguration(new CustomClientConfiguration(bookmark,
>                         new ThreadLocalHostnameDelegatingTrustManager(trust, bookmark.getProtocol().getSTSEndpoint()), key))
>                 .build()
> ```
> 
> and the field holding it if I need the `service` in subclasses of `STSAssumeRoleAuthorizationService` - is this on purpose?

I wouldn't mind the duplicated code required as long as only a single instance is required.

**Review by chenkins — APPROVED** [review]

**Comment by chenkins** [comment]
Fixes #15177

**Review by ylangisc — APPROVED** [review]

**Pull request merged**
